// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkp_sfm3L7bwaaKjGaouylrkGvjfzRuSk',
    appId: '1:152249207467:web:a574fb734fe466f89185ee',
    messagingSenderId: '152249207467',
    projectId: 'ulisses-xavier',
    authDomain: 'ulisses-xavier.firebaseapp.com',
    storageBucket: 'ulisses-xavier.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU0f1_rH1-rWfCf1fwsrZJRsKTn62mljc',
    appId: '1:152249207467:android:a7beddcb7b6fde009185ee',
    messagingSenderId: '152249207467',
    projectId: 'ulisses-xavier',
    storageBucket: 'ulisses-xavier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf92KOTn0YxO7n7N5dpIl03H9b263fCaE',
    appId: '1:152249207467:ios:9268deb72365caee9185ee',
    messagingSenderId: '152249207467',
    projectId: 'ulisses-xavier',
    storageBucket: 'ulisses-xavier.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf92KOTn0YxO7n7N5dpIl03H9b263fCaE',
    appId: '1:152249207467:ios:9268deb72365caee9185ee',
    messagingSenderId: '152249207467',
    projectId: 'ulisses-xavier',
    storageBucket: 'ulisses-xavier.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkp_sfm3L7bwaaKjGaouylrkGvjfzRuSk',
    appId: '1:152249207467:web:f00734321e4290a59185ee',
    messagingSenderId: '152249207467',
    projectId: 'ulisses-xavier',
    authDomain: 'ulisses-xavier.firebaseapp.com',
    storageBucket: 'ulisses-xavier.firebasestorage.app',
  );
}
